# Generated by Django 4.1.3 on 2022-12-05 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('father_name', models.CharField(max_length=50)),
                ('date_of_birth', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('aadhar_no', models.CharField(max_length=12)),
                ('profile', models.ImageField(null=True, upload_to='images/')),
                ('gender', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=8, null=True)),
            ],
            options={
                'db_table': 'user_details',
            },
        ),
        migrations.CreateModel(
            name='UserFeedbacksModel',
            fields=[
                ('feedback_id', models.AutoField(primary_key=True, serialize=False)),
                ('overall', models.IntegerField(help_text='data', null=True)),
                ('travelling', models.IntegerField(help_text='travelling', null=True)),
                ('suggestion', models.CharField(help_text='suggestion', max_length=400, null=True)),
                ('sentiment', models.CharField(help_text='sentiment', max_length=80, null=True)),
                ('feedback2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='userapp.usermodel')),
            ],
        ),
        migrations.CreateModel(
            name='NewPass',
            fields=[
                ('pass_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('aadhar', models.CharField(max_length=12, null=True)),
                ('payment_mode', models.CharField(max_length=50, null=True)),
                ('bus_travel_type', models.CharField(max_length=50, null=True)),
                ('mobile', models.CharField(max_length=50, null=True)),
                ('father', models.CharField(max_length=50, null=True)),
                ('date_of_birth', models.CharField(max_length=50, null=True)),
                ('gender', models.CharField(max_length=50, null=True)),
                ('pass_photo', models.ImageField(null=True, upload_to='images/')),
                ('passduration', models.CharField(max_length=50, null=True)),
                ('city', models.CharField(max_length=50, null=True)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('alldetails', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alldetails', to='userapp.usermodel')),
                ('pass_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_pass_details', to='userapp.usermodel')),
            ],
        ),
    ]
