# Generated by Django 4.1.3 on 2022-12-05 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserFeedbacksModel',
            new_name='UserFeedback',
        ),
    ]
