# Generated by Django 4.1.3 on 2022-12-05 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_alter_userfeedback_feedback2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfeedback',
            name='feedback2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.newpass'),
        ),
    ]
