# Generated by Django 4.1.3 on 2022-12-06 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_alter_userfeedback_feedback2'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentimentAnalysis',
            fields=[
                ('sentiment_id', models.AutoField(primary_key=True, serialize=False)),
                ('overall', models.IntegerField(help_text='data', null=True)),
                ('travelling', models.IntegerField(help_text='travelling', null=True)),
                ('suggestion', models.CharField(help_text='suggetion', max_length=400, null=True)),
                ('sentiment', models.CharField(help_text='sentiment', max_length=80, null=True)),
            ],
            options={
                'db_table': 'UserSentimentAnalysis',
            },
        ),
        migrations.AlterModelTable(
            name='userfeedback',
            table='UserFeedback_details',
        ),
    ]
