# Generated by Django 4.1.3 on 2022-12-06 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0006_sentimentanalysis_senti'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfeedback',
            name='feedback2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.usermodel'),
        ),
        migrations.DeleteModel(
            name='SentimentAnalysis',
        ),
    ]
